### ISSUE TITLE
Release v1.4

### ISSUE THREAD

**Issue by enoch85** [techandme/NextBerry#109]
This is stable now, and linked in the VM repo: https://github.com/nextcloud/vm#do-you-want-to-run-this-on-your-raspberry-pi

**Comment by WaaromZoMoeilijk** [comment]
https://github.com/techandme/NextBerry/commit/4a040e2c7c5c073fc46328f913306feffca5011d

**Comment by enoch85** [comment]
Thanks!

**Comment by enoch85** [comment]
https://github.com/techandme/NextBerry/releases/tag/V1.4
