### ISSUE TITLE
Let's encrypt certificate renewal, how to ?

### ISSUE THREAD

**Issue by newkindofworld** [techandme/NextBerry#118]
How do you renew let's encrypt certificate ?
Can't find any reference to it in the wiki or faq.
Sorry to bother :|

**Comment by newkindofworld** [comment]
Little advice please, my nextcloud is not operationnal due to let's encrypt expired :(

**Comment by newkindofworld** [comment]
Anyone ?

**Comment by Ark74** [comment]
I believe you are on the wrong place for this issue.
Please open a new issue on the Nextcloud virtual machine section.

In the meantime , use `certbot renew`
