### ISSUE TITLE
No maintenance for a while now?

### ISSUE THREAD

**Issue by enoch85** [techandme/NextBerry#119]
@ezraholm50 What's up? 

The scripts are pretty rock solid now in the VM, so I won't upgrade them as often as before. Please make this repo work with the latest patches in the VM. 

**Thank you**

**Comment by WaaromZoMoeilijk** [comment]
Wont be home for a while. Cant work on it, no time and a 20 KBs connection

**Comment by enoch85** [comment]
:(
