### ISSUE TITLE
Transfer this repo to Tech and Me

### ISSUE THREAD

**Issue by enoch85** [techandme/NextBerry#43]
1. Remove nextberry-vm in https://github.com/techandme
2. Hit transfer button in settings in this repo
3. Transfer to https://github.com/techandme
4. Rename the repo to `nextberry-vm`
4. `sed` all the whole folder with:
$~:{GITHUB_REPO_ROOT} `find . -type f -exec sed -i 's|ezraholm50/NextBerry|techandme/nextberry-vm|g' {} +`
5. Upload new .imgs to the server
6. Change links on www.techandme.se

If needed: https://developer.github.com/changes/2012-11-27-forking-to-organizations/ 
http://stackoverflow.com/questions/9023533/fork-as-organization-after-already-forking-in-github

**Comment by enoch85** [comment]
cc @ezraholm50

**Comment by WaaromZoMoeilijk** [comment]
Done

**Comment by enoch85** [comment]
Great!
