### ISSUE TITLE
How to update and upgrade safe and keep local conf on cron job

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [techandme/NextBerry#9]
I see there could be errors, updating grub for example, asking for user input. How to resolve this?

**Comment by enoch85** [comment]
I don't know ARM that well to answer this question, sorry.

**Comment by WaaromZoMoeilijk** [comment]
Do you have anything similar implemented for the 64 version? If so please
link me to it and I'll convert it.

**Comment by enoch85** [comment]
The update script doesn't ask the user for any input at all, it's designed that way.

**Comment by enoch85** [comment]
https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L32

**Comment by WaaromZoMoeilijk** [comment]
I was more aiming at regular apt update; apt full-upgrade -y cron jobs... Any idea or your 2 cents on that one?

**Comment by enoch85** [comment]
Why not use the script?
