### ISSUE TITLE
Setup crashing

### ISSUE THREAD

**Issue by newkindofworld** [techandme/NextBerry#99]
## Steps to reproduce
1. Created SD using Win32 Disk Imager (Samsung 64 Gb evo+)
2. First boot, then expanded system to full size of sd
3. Crashes after informing that creating a new user would be optimal

## Expected behaviour
setup should continue ?

## Actual behaviour
Error (see picture)

## Server configuration

**Server version:** (see your admin page)

**Raspberry 3**

**NextBerry latest**

**fresh install:**

## Network
**Do you use DHCP? yes**

**Is port 80 and/or 443 open? yes**

#### Screenshoots
http://imgur.com/a/UpU2C

**Comment by WaaromZoMoeilijk** [comment]
Could you link me to where you downloaded the image? Have you tried recreating the image on the SD? If that doesnt work try another SD card.

If that also doesnt solve your trouble, try holding shift every time it boots until the login screen. Please keep me updated.

**Comment by WaaromZoMoeilijk** [comment]
Any update?

**Comment by newkindofworld** [comment]
Sorry, I was a bit busy.
Downloaded from here : https://github.com/techandme/NextBerry/releases/tag/Images
I tried 3 times recreating the image, on same SD, crashes at different times. Tried another SD, same result.
Holding shift helped me to create the new sudo user, but then crashed with visual glitch on screen.
I'm beginning to suspect my Pi 3 is faulty, will try another one later.
I'll keep you updated.
Thanks for your help !

**Comment by WaaromZoMoeilijk** [comment]
Ive never seen this error before. Broadcom kernel stuff... I test everything on my PI3 l, Ill run it again later today to see if i can reproduce. 

Good one.. it could be your PI, do you have another one around?

Holding shift only delays the error?

**Comment by newkindofworld** [comment]
See the kind of errors I'm having now : 
http://imgur.com/a/1HDmg
http://imgur.com/a/6a5jd
I have to other Pi at home, I'm conducting tests at work, so I'll try in the next few hours.
Will get other SDs and power supply too, never know what could be faulty !

Holding shift only delays the errors indeed.

**Comment by WaaromZoMoeilijk** [comment]
Wow thats a rainbow of new errors. Id have to google around this weekend to check it out.

Mostly kernel panics are due to the overclocking i could try to create a custom image for you...

Please keep me updated ill do the same

**Comment by newkindofworld** [comment]
Never overclocked, don't even know how to do it.
I'll keep you updated with my new bunch of tests later today.
Thanks again !

**Comment by newkindofworld** [comment]
Nevermind, the Pi is somehow faulty, full setup runs flawlessly on another one.
Weird, as the first one is running fine a recalbox distro, retrogaming emulation and all; raspbian jessie too.
Thanks for your help, and sorry for the waste of time.

**Comment by WaaromZoMoeilijk** [comment]
Thats weird indeed, no problem thank you for reporting.

Not every PI is the same this is more so with overclocking some can handle it and some cant.

When the installation finishes You will be presented with a nice welcome screen and you can type: sudo install-log

This will give you a link to the installation log url please post it. That enables me to filter our bugs etc.

Glad to help, if any issues arise please let me know.

**Comment by newkindofworld** [comment]
Here it is

https://paste.ubuntu.com/24816930/

**Comment by WaaromZoMoeilijk** [comment]
Thank you very much. Does it auto redirect to https and does the nextcloud background image show in the browser?

**Comment by newkindofworld** [comment]
For the moment, it just advises me to enable https in administration settings, and I don't have yet the knowledge to do so (don't know where is the vhost config file to edit), I will go on with setup in the next few days.

**Comment by WaaromZoMoeilijk** [comment]
Thanks so the auto redirect is not working. Just add https:// before your url/ip in the browser and its all good.

**Comment by newkindofworld** [comment]
Simple indeed :)
I manage to add my dynamic dns domain to the trusted domains, so I can remote access nextcloud, it seems I have no background image at login form.
http://imgur.com/a/WESaR

**Comment by WaaromZoMoeilijk** [comment]
Yes thats a byproduct of the https error ill create a fix soon

**Comment by WaaromZoMoeilijk** [comment]
Please run:
`sed -i 's|  RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]|#  RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]|g' /var/www/nextcloud/.htaccess`

and:
`sed -i 's|  RewriteCond %{HTTPS} off|#  RewriteCond %{HTTPS} off|g' /var/www/nextcloud/.htaccess`

Then check in the browser if via https://url or ip the background image shows.

**Comment by enoch85** [comment]
For some strange reason you need a valid SSL cert for the background image to show. Same error on the VM. Run LE to sort it out.

**Comment by WaaromZoMoeilijk** [comment]
Ouch thats weird, I'd like to auto rewrite to https but adding this in .htaccess doesnt work for some reason. I think i'll add it to vhost:80

Last time i checked it was because of the images are beeing served over http instead of https...

Also just using snakeoil certs the background does display on LAN, on the PI.

**Comment by newkindofworld** [comment]
I did not setup LE as it was a first try, and I don't have a domain; is it working with ddns like no-ip ?
And if so, how can I run LE again ?

**Comment by WaaromZoMoeilijk** [comment]
Thats alright, you can use your ddns domain. You won't HAVE to use lets encrypt you can just add an exception for the current SSL cert.

If you want to try out lets encrypt run this:
sudo rm /var/scripts/activate-ssl.sh

sudo wget https://raw.githubusercontent.com/techandme/NextBerry/master/lets-encrypt/activate-ssl.sh -P /var/scripts/

sudo bash /var/scripts/activate-ssl.sh

Note that the script is still in BETA and can fail, haven't tested it myself. Running the full installation now to try it

@enoch85 this should be enough I think?
```
    cat << HTTP_CREATE > "$HTTP_CONF"
<VirtualHost *:80>

### YOUR SERVER ADDRESS ###
#    ServerAdmin admin@example.com
#    ServerName example.com
#    ServerAlias subdomain.example.com

### SETTINGS ###
    DocumentRoot $NCPATH

    <Directory $NCPATH>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
    Satisfy Any
    </Directory>

    <IfModule mod_dav.c>
    Dav off
    </IfModule>

    <Directory "$NCDATA">
    # just in case if .htaccess gets disabled
    Require all denied
    </Directory>

    SetEnv HOME $NCPATH
    SetEnv HTTP_HOME $NCPATH

    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

</VirtualHost>
HTTP_CREATE
```

**Comment by newkindofworld** [comment]
Just did the LE script, everything went fine, but now I can't access nextcloud web interface, locally or remotely, http error 500 using chrome.
(LE cert seems ok, as firefox shows the connection is secured using a LE cert)

**Comment by WaaromZoMoeilijk** [comment]
What domain did you use? Please post the output of: `cat /var/log/apache2/error.log`
Also reboot and see if that makes a difference. Also use https://yourdomain.com and try https://yourIPwan

Also try to figure out pressing the https properties in the address bar what domain the cert is for

**Comment by newkindofworld** [comment]
my dynamic dns is a ddns.net 
here's the output : https://pastebin.com/X73sdryP
Already rebooted twice.
Tried urls starting in https , and even on my wan ip directly, doesn't work, error.
I guess I messed up the config, as web interface isn't even responding locally using the Pi local ip (ssh ok though).

**Comment by WaaromZoMoeilijk** [comment]
Please post the output of: `cat /etc/apache2/sites-available/nextcloud_ssl_domain_self_signed.conf`

To see if it actually changed your domains, also post the out put of: `cat /var/log/syslog`
But use pastebin for this please.

**Comment by newkindofworld** [comment]
https://pastebin.com/86SzXG60
syslog is big, pasted it in 3 parts : 
https://pastebin.com/AtAmj7Mw
https://pastebin.com/4YiJRS9c
https://pastebin.com/MF9gGLRy

**Comment by WaaromZoMoeilijk** [comment]
Ok apache2 doesn't have your new certs yet. I'll post some how to's tonight ok?

**Comment by newkindofworld** [comment]
sure, I'm not in a hurry, whenever you have time, thanks again !

**Comment by WaaromZoMoeilijk** [comment]
Please post the output of: `ls /etc/letsencrypt/live; ls /etc/certbot/live`

Glad to help!

**Comment by newkindofworld** [comment]
root@synojerem:/home/ncadmin# ls /etc/letsencrypt/live; ls /etc/certbot/live
synojerem.ddns.net
ls: cannot access /etc/certbot/live: No such file or directory

**Comment by WaaromZoMoeilijk** [comment]
Please run this:

`sed -i 's|/etc/ssl/certs/ssl-cert-snakeoil.pem|/etc/letsencrypt/live/synojerem.ddns.net/cert.pem|g' /etc/apache2/sites-available/nextcloud_ssl_domain_self_signed.conf`

`sed -i 's|/etc/ssl/private/ssl-cert-snakeoil.key|/etc/letsencrypt/live/synojerem.ddns.net/privkey.pem|g' /etc/apache2/sites-available/nextcloud_ssl_domain_self_signed.conf`

`service apache2 restart`

Then try to visit:
https://synojerem.ddns.net/
https://79.88.156.242

If that works we'll try to redirect http to https automatically

**Comment by enoch85** [comment]
@ezraholm50 It's in the code already ;) https://github.com/nextcloud/vm/blob/master/lets-encrypt/activate-ssl.sh#L177-L180

@newkindofworld Great that LE worked on the rPI as well. :)

**Comment by WaaromZoMoeilijk** [comment]
@enoch85 yes when using LE but not when using the snakeoil certs.

**Comment by newkindofworld** [comment]
Tried the commands, still not working.
But I guess we're missing the point here, I can't even access nextcloud locally using local Pi address : 192.168.x.x , it gives the same error, shouldn't it be accessible locally ?

**Comment by enoch85** [comment]
@newkindofworld Please start over, download the latest image and run it from scratch. Also install SSL with Let's Encrypt when you get promted to do that (you need a domain for that btw). Then let us know the outcome.

**Comment by WaaromZoMoeilijk** [comment]
You are able to access SSH right? Please post the output of: cat /etc/apache2/sites-available/synojerem.ddns.net.conf

**Comment by newkindofworld** [comment]
Started over, everything runs fine now :)

Thanks again !

**Comment by enoch85** [comment]
Thanks for confirming.
